version: '3.8'

services:
  # Service A: Nexus-API (Backend)
  nexus-api:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      nexus-db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres@nexus-db:5432/inventory
      - SHADOW_DATABASE_URL=postgresql://postgres@nexus-db:5432/inventory_shadow
      - ADMIN_PASSWORD=admin1234
      - PRISMA_CLIENT_ENGINE_TYPE=library
    command: sh -c "npx prisma generate && npx prisma db push --accept-data-loss && npm start"

  # Service B: Nexus-DB (Database)
  nexus-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: inventory
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  # Service C: Ngrok (Public Tunnel)
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http nexus-api:4000
    environment:
      NGROK_AUTHTOKEN: 36x3DxOKGxt66UlL3G5YgZlZoOB_qfKW4m5sT1jeCT5b2Gne
    ports:
      - "4040:4040" # Dashboard UI untuk melihat URL Publik
    depends_on:
      - nexus-api

volumes:
  pg_data:
